package gui.controller;

import gui.Controller;
import gui.custom.PhoneCard;
import javafx.event.Event;
import javafx.fxml.FXML;

import javafx.scene.control.ListView;

public class BoardController extends Controller {

	@FXML
	private ListView<PhoneCard> myActiveList;
	@FXML
	private ListView<PhoneCard> myClosedList;
	@FXML
	private ListView<PhoneCard> participatingActiveList;
	@FXML
	private ListView<PhoneCard> participatingClosedList;

	@FXML
	public void expandList(Event event) {
		// TODO Autogenerated
	}
	
	@FXML
	private void initialize() {
		try {
			myActiveList.getItems().addAll(new PhoneCard(), new PhoneCard(), new PhoneCard(), new PhoneCard());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}