package gui.controller;

import gui.Controller;
import gui.custom.PhoneCard;
import javafx.event.Event;
import javafx.fxml.FXML;

import javafx.scene.control.ListView;

public class BoardController extends Controller {
	@FXML
	private ListView myActiveList;
	@FXML
	private ListView myClosedList;
	@FXML
	private ListView participatingActiveList;
	@FXML
	private ListView participatingClosedList;

	@FXML
	public void expandList(Event event) {
		// TODO Autogenerated
	}
	
	@FXML
	private void initialize() {
		try {
			myActiveList.getItems().add(new PhoneCard());
			myActiveList.getItems().add(new PhoneCard());
			myActiveList.getItems().add(new PhoneCard());
			myActiveList.getItems().add(new PhoneCard());
			myActiveList.getItems().add(new PhoneCard());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
