package gui.controller;

import gui.Controller;
import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;

public class ContainerController extends Controller {
	
	@FXML
	public void mainBoardAction(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void allPhonesAction(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void addPhoneAction(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void logoutAction(MouseEvent event) {
		// TODO Autogenerated
	}
}
