package gui.controller;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

public class ContainerController {

	
	@FXML
	public void mainBoardAction(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void allPhonesAction(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void addPhoneAction(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void logoutAction(MouseEvent event) {
		// TODO Autogenerated
	}
}
